### ISSUE TITLE
[Improvement] AV1 Codec

### ISSUE THREAD

**Issue by lavolpecheprogramma** [kopiro/tommy#20]
You can think to add the support to newest and more optimized format for web video!

This is a good article that explains the correct settings that you can use to convert a cross-browser video :)
https://evilmartians.com/chronicles/better-web-video-with-av1-codec

**Comment by kopiro** [comment]
@lavolpecheprogramma @vinzdef 
Implemented AV1, HEVC and H264 and removed generic MP4 container.

https://github.com/kopiro/tommy/pull/21/files
