### ISSUE TITLE
converter.webp : converts only the original picture and not the resized ones

### ISSUE THREAD

**Issue by lavolpecheprogramma** [kopiro/tommy#22]
Hello kopiro!
Is it possibile to enable tommy to convert all the picture sizes in webp too? 

Thank you <3

**Comment by kopiro** [comment]
You mean the resized one?

**Comment by kopiro** [comment]
https://github.com/kopiro/tommy/pull/23

**Comment by lavolpecheprogramma** [comment]
<3
